package packager

import (
	"github.com/krish567366/OpenTX/pkg/iso8583"
)

// VisaPackager implements Visa-specific ISO 8583 packaging
type VisaPackager struct {
	*GenericPackager
}

// NewVisaPackager creates a new Visa packager
func NewVisaPackager() *VisaPackager {
	specs := buildVisaFieldSpecs()
	generic := NewGenericPackager("VISA", specs)
	
	// Visa uses ASCII encoding for MTI and bitmap
	generic.SetMTIEncoding(iso8583.EncodingASCII, 4)
	generic.SetBitmapEncoding(iso8583.EncodingASCII)
	
	return &VisaPackager{
		GenericPackager: generic,
	}
}

func buildVisaFieldSpecs() map[int]*iso8583.FieldSpec {
	return map[int]*iso8583.FieldSpec{
		2: {
			ID:         2,
			Name:       "Primary Account Number",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeLLVAR,
			MaxLength:  19,
			Encoding:   iso8583.EncodingASCII,
		},
		3: {
			ID:         3,
			Name:       "Processing Code",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  6,
			Encoding:   iso8583.EncodingASCII,
			Padding:    iso8583.PaddingLeftZero,
		},
		4: {
			ID:         4,
			Name:       "Amount, Transaction",
			Type:       iso8583.FieldTypeAmount,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  12,
			Encoding:   iso8583.EncodingASCII,
			Padding:    iso8583.PaddingLeftZero,
		},
		7: {
			ID:         7,
			Name:       "Transmission Date & Time",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  10,
			Encoding:   iso8583.EncodingASCII,
		},
		11: {
			ID:         11,
			Name:       "Systems Trace Audit Number",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  6,
			Encoding:   iso8583.EncodingASCII,
			Padding:    iso8583.PaddingLeftZero,
		},
		12: {
			ID:         12,
			Name:       "Local Transaction Time",
			Type:       iso8583.FieldTypeTime,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  6,
			Encoding:   iso8583.EncodingASCII,
		},
		13: {
			ID:         13,
			Name:       "Local Transaction Date",
			Type:       iso8583.FieldTypeDate,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  4,
			Encoding:   iso8583.EncodingASCII,
		},
		14: {
			ID:         14,
			Name:       "Expiration Date",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  4,
			Encoding:   iso8583.EncodingASCII,
		},
		18: {
			ID:         18,
			Name:       "Merchant Category Code",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  4,
			Encoding:   iso8583.EncodingASCII,
		},
		22: {
			ID:         22,
			Name:       "POS Entry Mode",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  3,
			Encoding:   iso8583.EncodingASCII,
		},
		23: {
			ID:         23,
			Name:       "Card Sequence Number",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  3,
			Encoding:   iso8583.EncodingASCII,
			Padding:    iso8583.PaddingLeftZero,
		},
		25: {
			ID:         25,
			Name:       "POS Condition Code",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  2,
			Encoding:   iso8583.EncodingASCII,
		},
		32: {
			ID:         32,
			Name:       "Acquiring Institution ID",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeLLVAR,
			MaxLength:  11,
			Encoding:   iso8583.EncodingASCII,
		},
		35: {
			ID:         35,
			Name:       "Track 2 Data",
			Type:       iso8583.FieldTypeTrack,
			LengthType: iso8583.LengthTypeLLVAR,
			MaxLength:  37,
			Encoding:   iso8583.EncodingASCII,
		},
		37: {
			ID:         37,
			Name:       "Retrieval Reference Number",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  12,
			Encoding:   iso8583.EncodingASCII,
		},
		38: {
			ID:         38,
			Name:       "Authorization ID Response",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  6,
			Encoding:   iso8583.EncodingASCII,
		},
		39: {
			ID:         39,
			Name:       "Response Code",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  2,
			Encoding:   iso8583.EncodingASCII,
		},
		41: {
			ID:         41,
			Name:       "Card Acceptor Terminal ID",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  8,
			Encoding:   iso8583.EncodingASCII,
		},
		42: {
			ID:         42,
			Name:       "Card Acceptor ID Code",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  15,
			Encoding:   iso8583.EncodingASCII,
		},
		43: {
			ID:         43,
			Name:       "Card Acceptor Name/Location",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  40,
			Encoding:   iso8583.EncodingASCII,
		},
		48: {
			ID:         48,
			Name:       "Additional Data - Private",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeLLLVAR,
			MaxLength:  999,
			Encoding:   iso8583.EncodingASCII,
		},
		49: {
			ID:         49,
			Name:       "Transaction Currency Code",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  3,
			Encoding:   iso8583.EncodingASCII,
		},
		52: {
			ID:         52,
			Name:       "PIN Data",
			Type:       iso8583.FieldTypeBinary,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  8,
			Encoding:   iso8583.EncodingBinary,
		},
		53: {
			ID:         53,
			Name:       "Security Related Control Info",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  16,
			Encoding:   iso8583.EncodingASCII,
		},
		54: {
			ID:         54,
			Name:       "Additional Amounts",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeLLLVAR,
			MaxLength:  120,
			Encoding:   iso8583.EncodingASCII,
		},
		55: {
			ID:          55,
			Name:        "EMV Data",
			Type:        iso8583.FieldTypeTLV,
			LengthType:  iso8583.LengthTypeLLLVAR,
			MaxLength:   999,
			Encoding:    iso8583.EncodingBinary,
			Description: "ICC System Related Data",
		},
		60: {
			ID:         60,
			Name:       "Advice/Reason Code",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeLLLVAR,
			MaxLength:  999,
			Encoding:   iso8583.EncodingASCII,
		},
		61: {
			ID:         61,
			Name:       "POS Data",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeLLLVAR,
			MaxLength:  999,
			Encoding:   iso8583.EncodingASCII,
		},
		62: {
			ID:         62,
			Name:       "Custom Payment Service Fields",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeLLLVAR,
			MaxLength:  999,
			Encoding:   iso8583.EncodingASCII,
		},
		63: {
			ID:         63,
			Name:       "Network Data",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeLLLVAR,
			MaxLength:  999,
			Encoding:   iso8583.EncodingASCII,
		},
		64: {
			ID:         64,
			Name:       "Message Authentication Code",
			Type:       iso8583.FieldTypeBinary,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  8,
			Encoding:   iso8583.EncodingBinary,
		},
		90: {
			ID:         90,
			Name:       "Original Data Elements",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  42,
			Encoding:   iso8583.EncodingASCII,
		},
		95: {
			ID:         95,
			Name:       "Replacement Amounts",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  42,
			Encoding:   iso8583.EncodingASCII,
		},
		100: {
			ID:         100,
			Name:       "Receiving Institution ID",
			Type:       iso8583.FieldTypeNumeric,
			LengthType: iso8583.LengthTypeLLVAR,
			MaxLength:  11,
			Encoding:   iso8583.EncodingASCII,
		},
		102: {
			ID:         102,
			Name:       "Account ID 1",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeLLVAR,
			MaxLength:  28,
			Encoding:   iso8583.EncodingASCII,
		},
		103: {
			ID:         103,
			Name:       "Account ID 2",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeLLVAR,
			MaxLength:  28,
			Encoding:   iso8583.EncodingASCII,
		},
		120: {
			ID:         120,
			Name:       "Record Data",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeLLLVAR,
			MaxLength:  999,
			Encoding:   iso8583.EncodingASCII,
		},
		123: {
			ID:         123,
			Name:       "POS Data Code",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeLLLVAR,
			MaxLength:  999,
			Encoding:   iso8583.EncodingASCII,
		},
		125: {
			ID:         125,
			Name:       "Network Settlement Data",
			Type:       iso8583.FieldTypeAlphanumeric,
			LengthType: iso8583.LengthTypeLLLVAR,
			MaxLength:  999,
			Encoding:   iso8583.EncodingASCII,
		},
		128: {
			ID:         128,
			Name:       "Message Authentication Code",
			Type:       iso8583.FieldTypeBinary,
			LengthType: iso8583.LengthTypeFixed,
			MaxLength:  8,
			Encoding:   iso8583.EncodingBinary,
		},
	}
}
